#!/bin/bash -x
CONTAINER_NAME="mysql_docker"
TEMP_PASSWORD=""
SLEEP_TIME=10
NEW_PASSWORD="{mysql_root_password}"
DATABASE_NAME="{mysql_database}"
SCRIPT_FILE="mysql_commands.sql"

# install docker and pull MySQL image
sudo yum update -y
sudo yum install -y docker
sudo service docker start
sudo usermod -aG docker ec2-user
docker pull mysql/mysql-server:latest
docker run --name="$CONTAINER_NAME" -e MYSQL_ROOT_HOST=% -p 3306:3306 -d mysql/mysql-server

# Attempting to extract the temporary password generated by MySQL
# This is done in a loop until MySQL logs it.
while [ -z "$TEMP_PASSWORD" ]; do
    TEMP_PASSWORD=$(docker logs "$CONTAINER_NAME" 2>/dev/null | grep -oP "(?<=GENERATED ROOT PASSWORD: ).*")
    if [ -z "$TEMP_PASSWORD" ]; then
        echo "Password not found in logs. Sleeping for $SLEEP_TIME seconds..."
        sleep "$SLEEP_TIME"
    fi
done

# Generating SQL Script file to configure MySQL
echo "Sleeping for $SLEEP_TIME seconds before attempting to connect to MySQL..."
sleep "$SLEEP_TIME"
cat <<EOF > "$SCRIPT_FILE"
-- Reset root user password
ALTER USER 'root'@'localhost' IDENTIFIED BY '$NEW_PASSWORD';
ALTER USER 'root'@'%' IDENTIFIED BY '$NEW_PASSWORD';

-- Create database
CREATE DATABASE $DATABASE_NAME;
USE $DATABASE_NAME;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

-- Create the crud table and insert records
CREATE TABLE \`crud\` (
  \`id\` int(11) NOT NULL,
  \`name\` varchar(60) NOT NULL,
  \`email\` varchar(30) NOT NULL,
  \`phone\` varchar(20) NOT NULL,
  \`city\` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
INSERT INTO \`crud\` (\`id\`, \`name\`, \`email\`, \`phone\`, \`city\`) VALUES
(40, 'divya', 'amohapatra7000@gmail.com', '9114950911', 'balasore'),
(42, 'Divyasundar sahu', 'amohapatra7000@gmail.com', '999999999', 'balasore'),
(43, 'arpita', 'amohapatra7000@gmail.com', '9114950911', 'balasore');
ALTER TABLE \`crud\` ADD PRIMARY KEY (\`id\`);
ALTER TABLE \`crud\` MODIFY \`id\` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;
COMMIT;
EOF

# run mysql with the script file inside the docker container
docker exec -i "$CONTAINER_NAME" mysql -uroot -p"$TEMP_PASSWORD" --connect-expired-password --silent < "$SCRIPT_FILE"

# clean up
rm -f "$SCRIPT_FILE"
exit 0
