AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  glPdfSearchUploadToSearchLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: gl-pdf-search-upload-to-search-lambda
      Handler: lambda_function.handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::032822161467:role/lambda-multirole'
      Layers:
        - 'arn:aws:lambda:us-east-1:032822161467:layer:pdf-search-aws-auth:1'
      VpcConfig:
        SecurityGroupIds:
          - 'sg-0ac3ef597cdb9b3a6'
          - 'sg-e7437fb3'
        SubnetIds:
          - 'subnet-a8eef986'
          - 'subnet-740dd539'
          - 'subnet-13f4e14f'
  glPdfSearchInterStoreBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: gl-pdf-search-inter-store-bucket
      # The following NotificationConfiguration is used to trigger the 
      # lambda function. But it cannot be used when the stack is created 
      # for the first time. After the stack is created, the following 
      # NotificationConfiguration can be added and the stack can be 
      # updated. This will trigger the Lambda function when a new PDF 
      # document is uploaded to the bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt glPdfSearchUploadToSearchLambda.Arn
  glPdfSearchUploadToSearchVpcEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: com.amazonaws.us-east-1.s3
      VpcEndpointType: Gateway
      VpcId: "vpc-2a735750"
      RouteTableIds: ["rtb-ecf65592"]
      PolicyDocument:
        Version: "2008-10-17"
        Statement:
          - Effect: "Allow"
            Principal: "*"
            Action: "*"
            Resource: "*"     
  glPdfSearchInterStoreEventUploadToSearch:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref glPdfSearchUploadToSearchLambda
      Action: 'lambda:invokeFunction'
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::gl-pdf-search-inter-store-bucket
