version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file pdftotxt.yaml --s3-bucket gl-pdf-search-artifacts-bucket --output-template-file lambdaoutput.yaml

artifacts:
  type: zip
  files:
    - lambdaoutput.yaml